[package]
name = "oracle-network"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "oracle_network"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
